spring:
  application:
    name: obvious-service-client

server:
  port: 8088

eureka:
  client:
    healthcheck:
      enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false